name: CI build pipeline

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
      
    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Install npm dependancies
      run: npm install

    - name: Build project
      run: npx ng build --prod --base-href /ng-covid19-tracker/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_SECRET }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
