name: CI deploy build

on:
  push:
    branches:
      - master

jobs:
  deplay:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Install npm dependancies
      run: npm install

    - name: Build project
      run: npx ng build --prod --base-href /ng-covid19-tracker/

    - name: Publish to github pages
      run: npx ngh --dir=dist/ng-covid19-tracker
